name: Trigger auto deployment for knsh-interview-exam

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/knsh-interview-exam-AutoDeployTrigger-429494bc-8bf2-4a50-aa9a-ea784c627c08.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.KNSHINTERVIEWEXAM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KNSHINTERVIEWEXAM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KNSHINTERVIEWEXAM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: knshinterviewexam.azurecr.io
          registryUsername: ${{ secrets.KNSHINTERVIEWEXAM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KNSHINTERVIEWEXAM_REGISTRY_PASSWORD }}
          containerAppName: knsh-interview-exam
          resourceGroup: use-for-personal
          imageToBuild: knshinterviewexam.azurecr.io/knsh-interview-exam:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


